name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest
  
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      
      - name: Run application in the background
        run: |
          nohup poetry run uvicorn punkapi.app:app --host 0.0.0.0 --port 5001 &

      - name: Wait for the application to start
        run: |
          sleep 10  # Adjust the sleep duration as needed

      
      - name: Run Locust performance tests
        run: |
          poetry run locust --headless -u 10 -r 1 -t 1m --html locust_report.html
      
      - name: Upload Locust report
        uses: actions/upload-artifact@v4
        with:
          name: locust-report
          path: locust_report.html